version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - ORIGIN_DOMAIN=${ORIGIN_DOMAIN}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/sala-de-conversacion2
    container_name: react_frontend
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
    container_name: nginx_server
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   # referencia al volumen declarado más abajo

volumes:
  postgres_data: {}  # <-- declarar el volumen vacío así
